export const projectRequestConfig = {
  enabled: true,
  id: 'project-request',
  tabLabel: 'Request a Quote',
  mobileLabel: 'Request a Quote',
  eyebrow: 'Project request',
  title: 'Tell us what you need.',
  description: 'Share the service you need, your timeline, and any important details.',
  websiteLabel: 'Website',
  serviceLabel: 'Service needed',
  budgetLabel: 'Budget range',
  timelineLabel: 'Timeline',
  messageLabel: 'Project details',
  messagePlaceholder: 'Tell us what you need help with.',
  consentLabel: 'You can contact me about this request.',
  submitLabel: 'Send Request',
  submittingLabel: 'Sending request…',
  successTitle: 'Request received.',
  successMessage: 'Thanks. Your request has been received.',
  nextStepTitle: 'What happens next?',
  nextStepText: 'Your request will be reviewed and followed up using the contact information you provide.',
  privacyText: 'By submitting, you are asking this business to contact you about your request.',
  errorMessage: 'Unable to submit your request right now.',
  closeLabel: 'Close',
  theme: { primary:'#2F6BFF', primaryHover:'#2458D8', primaryDark:'#1748BE' },
};
