export const JUSTCONSIGNIN_PAGES = [
  {
    id: 'home',
    title: 'Home',
    path: '/',
    source: 'src/website/pages/Home/Home.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Homepage with Shopify positioning, workflow highlights, videos and site links.',
  },
  {
    id: 'features',
    title: 'Features',
    path: '/features',
    source: 'src/website/pages/Features/Features.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Feature overview and store-type sections.',
  },
  {
    id: 'how-it-works',
    title: 'How It Works',
    path: '/how-it-works',
    source: 'src/website/pages/HowItWorks/HowItWorks.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Six-step intake-to-payout workflow and problem/solution content.',
  },
  {
    id: 'pricing',
    title: 'Pricing',
    path: '/pricing',
    source: 'src/website/pages/Pricing/Pricing.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Trial, plan details and pricing feature lists.',
  },
  {
    id: 'faq',
    title: 'FAQ',
    path: '/faq',
    source: 'src/website/pages/FAQ/FAQ.jsx',
    kind: 'structured',
    editor: 'custom',
    description: 'FAQ groups plus FAQPage structured data.',
  },
  {
    id: 'blog',
    title: 'Blog',
    path: '/blog',
    source: 'src/website/pages/Blog/Blog.jsx',
    kind: 'content',
    editor: 'blog',
    description: 'Blog index. Individual posts continue to be managed under Blog Posts.',
  },
  {
    id: 'contact',
    title: 'Contact',
    path: '/contact',
    source: 'src/website/pages/Contact/Contact.jsx',
    kind: 'marketing',
    editor: 'visual',
    description: 'Support contact information and help instructions.',
  },
  {
    id: 'partner-program',
    title: 'Founding Partner Program',
    path: '/partner-program',
    aliases: ['/beta'],
    source: 'src/website/pages/Beta/Beta.jsx',
    kind: 'form',
    editor: 'custom',
    description: 'Founding Partner / beta landing page and application form.',
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    path: '/privacy',
    source: 'src/website/pages/Legal/Privacy.jsx',
    kind: 'legal',
    editor: 'visual',
    description: 'Public privacy policy.',
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    path: '/terms',
    source: 'src/website/pages/Legal/Terms.jsx',
    kind: 'legal',
    editor: 'visual',
    description: 'Public terms of service.',
  },
  {
    id: 'shopify-app',
    title: 'Shopify App Demo',
    path: '/shopify-app',
    aliases: ['/demo → /shopify-app'],
    source: 'src/website/demo-app/ShopifyAppPreview.jsx',
    kind: 'application',
    editor: 'custom',
    description: 'Interactive Shopify app demo. This is application UI rather than a normal marketing page.',
  },
];

export const JUSTINDEMATTEIS_PAGES = [
  {
    id: 'home',
    title: 'Home',
    path: '/',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'Portfolio homepage with positioning, featured work and calls to action.',
  },
  {
    id: 'skills',
    title: 'Skills',
    path: '/skills',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Expanded SEO, ecommerce, WordPress, Adobe and development capabilities.',
  },
  {
    id: 'work',
    title: 'Work Experience',
    path: '/work',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Professional ecommerce and development experience with linked case studies.',
  },
  {
    id: 'work-template',
    title: 'Case Study — Website',
    path: '/work/template',
    source: 'Work Posts',
    kind: 'content',
    editor: 'work-post',
    editorTarget: '/admin/work-posts/9001c003-00a3-492b-870b-27b249a5b2b4',
    description: 'Website Shopify consignment software case study.',
  },
  {
    id: 'work-jill',
    title: 'Case Study — Jill & The Beanstalk',
    path: '/work/jill-and-the-beanstalk',
    source: 'Work Posts',
    kind: 'content',
    editor: 'work-post',
    editorTarget: '/admin/work-posts/bde69606-b7cc-4efd-8d1e-03ea70e9ec86',
    description: 'Jill & The Beanstalk Shopify ecommerce, SEO and growth case study.',
  },
  {
    id: 'work-wheels',
    title: 'Case Study — Wheels Automotive',
    path: '/work/wheels-automotive',
    source: 'Work Posts',
    kind: 'content',
    editor: 'work-post',
    editorTarget: '/admin/work-posts/e2bffca9-7d77-4cea-9750-5fb14da80d89',
    description: 'Wheels Automotive Adobe Commerce / Magento B2B ecommerce case study.',
  },
  {
    id: 'work-wordpress',
    title: 'Case Study — WordPress Websites',
    path: '/work/wordpress-websites',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Grouped WordPress and Elementor client website work.',
  },
  {
    id: 'ai-development',
    title: 'AI + Development',
    path: '/ai-development',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'How AI is used as part of the development and problem-solving workflow.',
  },
  {
    id: 'about',
    title: 'About',
    path: '/about',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    description: 'Career story, engineering background and transition into software development.',
  },
  {
    id: 'blog',
    title: 'Blog',
    path: '/blog',
    source: 'shared blog manager',
    kind: 'content',
    editor: 'blog',
    description: 'Articles and development notes for the portfolio.',
  },
  {
    id: 'contact',
    title: 'Contact',
    path: '/contact',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    description: 'Employment, freelance and collaboration contact page.',
  },
];


export const SUNWINGS_PAGES = [
  {
    id: 'home',
    title: 'Home',
    path: '/',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    editorTarget: '/admin/template/pages/home',
    description: 'Website homepage. Services and locations are pulled from their post types.',
  },
  {
    id: 'services',
    title: 'Services',
    path: '/services',
    source: 'shared page builder + Service Posts',
    kind: 'marketing',
    editor: 'visual',
    editorTarget: '/admin/template/pages/services',
    description: 'Main services index page. Individual services stay in Service Posts.',
  },
  {
    id: 'locations',
    title: 'Service Areas',
    path: '/locations',
    source: 'shared page builder + Location Posts',
    kind: 'marketing',
    editor: 'visual',
    editorTarget: '/admin/template/pages/locations',
    description: 'Main service-area index page. Individual areas stay in Location Posts.',
  },
  {
    id: 'pricing',
    title: 'Pricing',
    path: '/pricing',
    source: 'shared page builder',
    kind: 'marketing',
    editor: 'visual',
    editorTarget: '/admin/template/pages/pricing',
    description: 'Pricing, quote guidance and price-match messaging.',
  },
  {
    id: 'contact',
    title: 'Contact',
    path: '/contact',
    source: 'shared page builder + quote form',
    kind: 'form',
    editor: 'visual',
    editorTarget: '/admin/template/pages/contact',
    description: 'Contact information and the Website quote-request form.',
  },
  {
    id: 'blog',
    title: 'Moving Tips',
    path: '/blog',
    source: 'shared page builder',
    kind: 'content',
    editor: 'visual',
    editorTarget: '/admin/template/pages/blog',
    description: 'Moving Tips index page.',
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    path: '/privacy',
    source: 'shared page builder',
    kind: 'legal',
    editor: 'visual',
    editorTarget: '/admin/template/pages/privacy',
    description: 'Website privacy policy.',
  },
];

export const WEBSITE_PAGES = JUSTCONSIGNIN_PAGES;

export function getWebsitePages(siteKey = 'template') {
  if (siteKey === 'template') return JUSTINDEMATTEIS_PAGES;
  if (siteKey === 'template') return SUNWINGS_PAGES;
  return JUSTCONSIGNIN_PAGES;
}

export function getWebsitePage(id, siteKey = 'template') {
  return getWebsitePages(siteKey).find(page => page.id === id) || null;
}

export function livePageUrl(path, siteKey = 'template') {
  const domain = siteKey === 'template'
    ? 'template.com'
    : siteKey === 'template'
      ? 'templatetransport.ca'
      : 'template.com';
  const prefix = siteKey === 'template' ? 'https://' : 'https://www.';
  return `${prefix}${domain}${path === '/' ? '' : path}`;
}


const block = (type, id, props) => ({ type, props: { id, ...props } });
const heading = (id, text, level = 'h2') => block('HeadingBlock', id, { text, level, align: 'left' });
const text = (id, value) => block('TextBlock', id, { text: value, align: 'left' });
const hero = (id, eyebrow, headingText, body) => block('HeroBlock', id, {
  eyebrow,
  heading: headingText,
  accent: '',
  headingSize: 'medium',
  text: body,
  primaryButtonText: '',
  primaryButtonUrl: '',
  secondaryButtonText: '',
  secondaryButtonUrl: '',
  note: '',
  image: '',
  imageAlt: '',
  background: 'light',
});
const cta = (id, headingText, body, buttonText, buttonUrl) => block('CtaBlock', id, {
  heading: headingText,
  text: body,
  buttonText,
  buttonUrl,
  background: 'dark',
});

const PAGE_EDITOR_DATA = {
  home: {
    content: [
      block('HomeHeroBlock', 'home-hero', {
        brandText: 'Consignment management built for Shopify stores',
        eyebrow: 'Website for Shopify',
        heading: 'Create consignment products from your phone and sell them through Shopify.',
        text: 'Website connects consignors, inventory, Shopify products, POS sales and payouts in one workflow — without spreadsheets or duplicate entry.',
        primaryButtonText: 'Open Shopify app demo',
        primaryButtonUrl: '/shopify-app',
        watchButtonText: 'Watch videos',
        watchButtonUrl: '#home-video-heading',
        partnerButtonText: 'Founding Partner Program',
        partnerButtonUrl: '/partner-program',
        note1: 'Create products from your phone',
        note2: 'Shopify POS ready',
        note3: 'Track consignor payouts',
        panelTitle: 'Shopify connected',
        panelSubtitle: 'Products · POS · Consignment',
        panelDate: 'Today',
        panelHeading: 'Consignment overview',
        metric1Label: 'Consignors',
        metric1Value: '24',
        metric2Label: 'Available items',
        metric2Value: '118',
        metric3Label: 'Sales',
        metric3Value: '$3,840',
        metric4Label: 'Owed',
        metric4Value: '$1,426',
        person1Initials: 'SM',
        person1Name: 'Sarah Miller',
        person1Detail: '4 items · $84.00 due',
        person1Percent: '60%',
        person2Initials: 'DR',
        person2Name: 'Daniel Reed',
        person2Detail: '2 items · $35.00 due',
        person2Percent: '50%',
      }),
      block('HomeIntegrationBlock', 'home-shopify', {
        eyebrow: 'Built around Shopify',
        heading: 'Intake, product creation and POS in one consignment workflow.',
        text: 'Use Website to manage the consignment details Shopify does not track on its own, while keeping the product and sale inside your Shopify workflow.',
        card1Heading: 'Create Shopify products from your phone',
        card1Text: 'Enter the consignor and item once, add the product details and photo, then create the Shopify product directly from intake.',
        card2Heading: 'Sell consignment items at the point of sale',
        card2Text: 'Publish items to Shopify POS and keep the consignment item tied back to the correct consignor when it sells.',
        card3Heading: 'Know exactly what each consignor is owed',
        card3Text: 'Track sold-unpaid items, commission splits, payouts and transaction history without maintaining a second spreadsheet.',
      }),
      block('HomeVideosBlock', 'home-videos', {
        eyebrow: 'Watch the Shopify workflow',
        heading: 'See Website in action.',
      }),
      block('HomeLinksBlock', 'home-links', {
        link1Title: 'Shopify features',
        link1Text: 'Products, POS, consignors, sales, payouts and reporting.',
        link1Url: '/features',
        link2Title: 'How it works',
        link2Text: 'Follow the Shopify consignment workflow from intake through payout.',
        link2Url: '/how-it-works',
        link3Title: 'Open the Shopify app demo',
        link3Text: 'Explore the Website interface and connected workflow.',
        link3Url: '/shopify-app',
      }),
    ],
    root: { props: {} },
  },

  features: {
    content: [
      block('FeaturesHeroBlock', 'features-hero', {
        brandText: 'Built for Shopify consignment stores',
        eyebrow: 'Features',
        heading: 'Move consignment inventory from intake to sale faster.',
        text: 'Website is built for Shopify store owners who process lots of unique consignment and resale inventory. Enter items quickly, create Shopify products without duplicate entry, track every sale back to the correct consignor and keep payouts organized in one workflow.',
        image: '',
        imageAlt: '',
        imagePosition: 'right',
      }),
      block('FeaturesGridBlock', 'features-grid', {
        eyebrow: 'Made for real resale workflows',
        heading: 'When every item is different, intake speed matters.',
        text: 'Traditional retail receives repeatable SKUs from suppliers. Consignment and resale stores often receive one-of-a-kind items in batches. Website focuses on making that store-owner workflow faster and easier to manage from the moment inventory comes in.',
        item1Title: 'Built for high-volume resale inventory',
        item1Text: 'Website is designed for consignment and resale stores that receive lots of unique items. Move quickly from an item in hand to a complete consignment record without relying on paper notes or spreadsheets.',
        item2Title: 'Consignor accounts',
        item2Text: 'Keep contact details, commission split, notes, balances and every item connected to the correct consignor.',
        item3Title: 'Fast mobile item intake',
        item3Text: 'Create consignors and add items from your phone while you are receiving inventory. Enter the item once, add product details and photos, and keep the intake process moving.',
        item4Title: 'Create Shopify products without duplicate entry',
        item4Text: 'Turn a consignment item into a Shopify product without typing the same information into a second system. Publish to Shopify POS and choose whether the item should also be available online.',
        item5Title: 'Shopify POS, online and manual sales tracking',
        item5Text: 'Keep each consignment item tied to the correct consignor whether it sells in-store through Shopify POS, through your Shopify online store, or through a manual sale workflow.',
        item6Title: 'Payout management',
        item6Text: 'See sold-unpaid items, calculate the consignor share and record payouts while preserving the full sale and payout history.',
        item7Title: 'Reports and transactions',
        item7Text: 'Review sales, consignor earnings, payout history and transaction activity from the same workspace so you always know what sold and what is still owed.',
        item8Title: 'Import and export for larger inventories',
        item8Text: 'Bulk import consignors and items from CSV and keep downloadable data tools available when you are moving existing inventory into Website or maintaining your own records.',
      }),
      block('FeaturesAudienceBlock', 'features-audience', {
        eyebrow: 'Who Website is for',
        heading: 'Shopify stores with a lot of unique resale inventory to enter and track.',
        text: 'The common problem is volume: many individual items, many consignors and a constant need to know who owns what, what sold and what each person is owed.',
        item1Title: 'Consignment & resale shops',
        item1Text: 'Stores taking in a steady flow of one-of-a-kind inventory from consignors.',
        item2Title: 'Secondhand & thrift-style stores',
        item2Text: 'Shops using Shopify that need a faster way to enter and manage large amounts of resale inventory tied to individual consignors.',
        item3Title: 'Children’s & family resale',
        item3Text: 'Clothing, toys, baby gear and other categories where many unique items can arrive from the same consignor at once.',
        item4Title: 'Vintage & clothing stores',
        item4Text: 'Apparel, accessories and vintage inventory where every item may need its own title, price, photos and consignor record.',
        item5Title: 'Furniture & home décor consignment',
        item5Text: 'Larger one-off pieces that need ownership, pricing, sale status and payout information kept together.',
        item6Title: 'Specialty resale stores',
        item6Text: 'Sporting goods, collectibles, designer goods and other resale businesses handling unique inventory through Shopify.',
      }),
      block('FeaturesCtaBlock', 'features-cta', {
        heading: 'Spend less time entering inventory and more time selling it.',
        text: 'Explore consignors, fast mobile intake, Shopify product creation, POS and online sales tracking, and payouts in the working app demo.',
        buttonText: 'Open Shopify App Demo',
        buttonUrl: '/shopify-app',
      }),
    ],
    root: { props: {} },
  },

  'how-it-works': {
    content: [
      hero(
        'how-hero',
        'How it works',
        'From consignment intake to Shopify sale to payout.',
        'Enter the consignor and item once. Website carries that information through Shopify product creation, selling and the final consignor payout.'
      ),
      heading('how-01-title', '01 · Create the consignor'),
      text('how-01-copy', 'Add the consignor number, contact information, commission split and notes so every item stays tied to the right person.'),
      heading('how-02-title', '02 · Add the item from your phone'),
      text('how-02-copy', 'Enter the item details, asking price, condition and photo while you are receiving the inventory.'),
      heading('how-03-title', '03 · Create the Shopify product'),
      text('how-03-copy', 'Use the same intake record to create the Shopify product and publish it to Shopify POS, with optional online publishing when needed.'),
      heading('how-04-title', '04 · Sell through Shopify'),
      text('how-04-copy', 'Sell the product through Shopify POS or your connected sales workflow while Website keeps the consignment record attached to the consignor.'),
      heading('how-05-title', '05 · Review what is owed'),
      text('how-05-copy', 'Sold-unpaid items appear in the payout workflow with the sale price, commission split and consignor share already connected.'),
      heading('how-06-title', '06 · Pay the consignor and keep the history'),
      text('how-06-copy', 'Record the payout method, date and included items. Sales, payouts and transaction history remain available for reporting.'),
      heading('how-problem-1', 'How to avoid duplicate entry when adding consignment products to Shopify'),
      text('how-problem-1-copy', 'Enter the item during intake, then use that same Website record to create the Shopify product. The product details do not need to be maintained once in a spreadsheet and typed again later in Shopify.'),
      heading('how-problem-2', 'Streamlining consignment intake from your phone'),
      text('how-problem-2-copy', 'Add the consignor, item details and photos while inventory is being received. Mobile intake is designed to move the item directly into the Shopify product workflow without waiting for a separate desktop data-entry step.'),
      heading('how-problem-3', 'How to keep Shopify POS sales connected to consignor payouts'),
      text('how-problem-3-copy', 'Each item remains tied to its consignor. When the item sells through the connected Shopify workflow, the sale, commission split and amount owed can move into the sold-unpaid and payout workflow together.'),
      heading('how-problem-4', 'Managing one-of-a-kind consignment inventory without separate spreadsheets'),
      text('how-problem-4-copy', 'Website keeps the item record, Shopify connection, sale status and payout history together so stores can follow individual consignment pieces without maintaining separate intake, sales and payout files.'),
      cta('how-cta', 'Run intake from the counter, floor or your phone.', 'The goal is simple: fewer spreadsheets, less duplicate entry and a clear connection between the Shopify product and the person who consigned it.', 'Open Shopify App Demo', '/shopify-app'),
    ],
    root: { props: {} },
  },

  pricing: {
    content: [
      hero(
        'pricing-hero',
        'Pricing',
        'Website for Shopify includes a 14-day free trial.',
        'Website brings consignors, Shopify product creation, POS sales and payouts into one workflow. Account onboarding is being finalized; the app demo is available now.'
      ),
      heading('pricing-plan-title', 'Website for Shopify'),
      text('pricing-plan-price', '14-day free trial'),
      text('pricing-plan-note', 'The 14-day free trial will be available when account onboarding opens.'),
      heading('pricing-features-title', 'Included', 'h3'),
      text('pricing-features-copy', 'Consignor management · Mobile item intake · Create Shopify products · Shopify POS publishing · Optional online publishing · Manual sale tracking · Sales and payouts · Transactions and reports · CSV import / export'),
      text('pricing-plan-shopify-copy', 'Create products from your phone, publish to Shopify POS and keep each sale connected to the correct consignor.'),
      heading('pricing-advanced-title', 'Advanced', 'h3'),
      text('pricing-advanced-copy', 'Coming later. For larger operations that need additional locations and workflows.'),
    ],
    root: { props: {} },
  },

  contact: {
    content: [
      hero('contact-hero', 'Contact', 'Need help with Website?', 'For support, account questions, setup help, or general inquiries, email us directly.'),
      heading('contact-email-title', 'Email support', 'h3'),
      text('contact-email-copy', 'support@template.com'),
      heading('contact-include-title', 'What to include', 'h3'),
      text('contact-include-copy', 'If you are reporting a problem, include the page you were on, what you were trying to do, and a screenshot if possible.'),
      heading('contact-response-title', 'Response', 'h3'),
      text('contact-response-copy', 'We will respond through the support email address you contact us from.'),
    ],
    root: { props: {} },
  },

  privacy: {
    content: [
      hero('privacy-hero', 'Privacy', 'Privacy policy', 'Last updated: August 2026'),
      heading('privacy-collect-title', 'Information we collect'),
      text('privacy-collect-copy', 'Website processes account information such as your name, business name, email address and authentication information. When you use the service, you may also enter consignor contact information, inventory records, sale records, payout records, notes and business settings.'),
      heading('privacy-use-title', 'How we use information'),
      text('privacy-use-copy', 'We use information to provide and secure the service, maintain your workspace, calculate and record consignment activity, provide customer support, process subscriptions, prevent abuse and improve reliability.'),
      heading('privacy-providers-title', 'Service providers'),
      text('privacy-providers-copy', 'Production deployments may use hosting, database/authentication, payment and email providers. These providers process information only as needed to provide their services. Payment card details are handled by the payment provider and are not intended to be stored directly by Website.'),
      heading('privacy-consignor-title', 'Your consignor data'),
      text('privacy-consignor-copy', 'You are responsible for having an appropriate basis to enter and use personal information belonging to your consignors. Do not enter sensitive information that is not necessary for consignment management.'),
      heading('privacy-retention-title', 'Retention and deletion'),
      text('privacy-retention-copy', 'Workspace information is retained while an account is active and for a reasonable period afterward when needed for recovery, fraud prevention, legal obligations or support. Account owners may request deletion of their account and workspace, subject to records we are required to retain.'),
      heading('privacy-security-title', 'Security'),
      text('privacy-security-copy', 'We use access controls, protected server credentials and third-party authentication/payment services designed to reduce unauthorized access. No online service can guarantee absolute security.'),
      heading('privacy-contact-title', 'Contact'),
      text('privacy-contact-copy', 'Privacy questions and deletion requests should be sent using the support contact published by Website.'),
      text('privacy-launch-note', 'Launch draft: have this policy reviewed for the jurisdictions where you operate before accepting production customers.'),
    ],
    root: { props: {} },
  },

  terms: {
    content: [
      hero('terms-hero', 'Terms', 'Terms of service', 'Last updated: August 2026'),
      heading('terms-use-title', 'Using Website'),
      text('terms-use-copy', 'You may use Website to manage legitimate consignment and resale operations. You are responsible for the accuracy of information entered into your workspace, your staff’s access, and complying with laws that apply to your business and consignors.'),
      heading('terms-trial-title', '14-day free trial and subscriptions'),
      text('terms-trial-copy', 'New paid-plan signups may begin with a 14-day free trial. A valid payment method may be required to start the trial. Unless the subscription is cancelled before the trial ends, the selected recurring subscription will begin and the payment provider may charge the payment method on file according to the price shown at checkout.'),
      heading('terms-billing-title', 'Billing and cancellation'),
      text('terms-billing-copy', 'Subscriptions renew automatically until cancelled. Account owners can manage payment details and cancellation through the billing portal when production billing is enabled. Cancellation stops future renewal; access may continue through the end of the current paid or trial period depending on billing configuration. Fees already charged are non-refundable except where required by law or expressly stated otherwise.'),
      heading('terms-accounts-title', 'Accounts and security'),
      text('terms-accounts-copy', 'You must provide accurate account information and protect your login credentials. You are responsible for activity performed through your account and should notify support if you believe access has been compromised.'),
      heading('terms-acceptable-title', 'Acceptable use'),
      text('terms-acceptable-copy', 'Do not use the service to break the law, infringe rights, distribute malicious software, attempt unauthorized access, interfere with the service, or store information you do not have a lawful reason to process.'),
      heading('terms-availability-title', 'Availability and changes'),
      text('terms-availability-copy', 'We may update features, correct errors, perform maintenance, or change service availability. We aim to provide a reliable service but do not guarantee uninterrupted or error-free operation.'),
      heading('terms-data-title', 'Your data'),
      text('terms-data-copy', 'You retain responsibility for business and consignor information you enter. You grant Website the limited rights necessary to host, process and back up that information to provide the service.'),
      heading('terms-termination-title', 'Termination'),
      text('terms-termination-copy', 'Accounts may be suspended or terminated for non-payment, abuse, security risk or material violation of these terms. You may stop using the service and cancel your subscription through the available billing controls.'),
      heading('terms-liability-title', 'Liability'),
      text('terms-liability-copy', 'To the extent permitted by law, Website is provided without guarantees beyond those expressly stated, and liability is limited to the extent allowed by applicable law.'),
      text('terms-launch-note', 'Launch draft: have these terms reviewed for the jurisdictions where you operate and confirm the final price/refund policy before accepting production customers.'),
    ],
    root: { props: {} },
  },
};


const JUSTIN_PAGE_EDITOR_DATA = {
  home: {
    content: [
      block('ShowcaseHeroBlock', 'justin-home-showcase', {
        eyebrow: 'Developer • Product Builder • Problem Solver',
        heading: 'I build digital products that',
        accent: 'solve real problems.',
        text: 'Web applications, Shopify solutions, ecommerce systems, automation and AI-assisted development — from the first idea through testing, refinement and deployment.',
        primaryButtonText: 'View my work →',
        primaryButtonUrl: '/work',
        secondaryButtonText: 'How I work with AI',
        secondaryButtonUrl: '/ai-development',
        note: 'Based in Ontario, Canada • Building real products for real business workflows',
        cardBadge: 'FEATURED PROJECT',
        cardTitle: 'Website — Shopify consignment management built from a real store problem.',
        cardText: 'A working product connecting consignors, inventory, Shopify products, POS sales and payouts.',
        flow1: 'Intake', flow2: 'Shopify', flow3: 'Sold', flow4: 'Paid',
      }),
      block('ProofStripBlock', 'justin-home-proof', {
        item1Title: 'Real products', item1Text: 'Not mockups built only for a portfolio.',
        item2Title: 'Real workflows', item2Text: 'Software designed around actual business needs.',
        item3Title: 'AI-assisted', item3Text: 'Faster prototyping, debugging, iteration and delivery.',
      }),
      block('CaseStudyBlock', 'justin-home-case-study', {
        eyebrow: 'Featured case study',
        sectionHeading: 'From a real store problem to a working Shopify product.',
        sectionText: 'Website grew from a real consignment workflow problem into a Shopify-focused application for managing consignors, products, sales and payouts.',
        projectEyebrow: 'Website',
        projectHeading: 'Build around the business. Not the other way around.',
        projectText: 'The goal was not to build another spreadsheet. It was to remove duplicate entry, connect consignment inventory to Shopify, support mobile intake, track sold items and make consignor payouts easier to understand.',
        tags: 'Shopify, React, POS, Supabase, Mobile Intake, Payouts',
        buttonText: 'Read the story →', buttonUrl: '/work/template',
        workflowTitle: 'Consignment workflow',
        step1: 'Create consignor + item',
        step2: 'Publish to Shopify POS / Online Store',
        step3: 'Track the sale back to the consignor',
        step4: 'Calculate and complete payout',
      }),
      block('CardGridBlock', 'justin-home-work-grid', {
        item1Eyebrow:'Professional work',item1Title:'Wheels Automotive',item1Text:'Adobe Commerce / Magento, B2B ecommerce, frontend components, QA, product/category content, SEO and launch support.',item1Icon:'WA',item1Style:'dark',
        item2Eyebrow:'Custom business tools',item2Title:'Internal tools & admin systems',item2Text:'Dashboards, data-entry workflows, admin tools and interfaces designed around how people actually perform the work.',item2Icon:'UI',item2Style:'white',
        item3Eyebrow:'Ecommerce',item3Title:'Shopify & commerce integrations',item3Text:'Product workflows, POS-connected applications, publishing controls and custom ecommerce experiences.',item3Icon:'EC',item3Style:'blue',
        item4Eyebrow:'AI-assisted development',item4Title:'From idea to working software faster.',item4Text:'AI supports architecture, prototyping, debugging, refactoring, UX exploration, research and documentation while product direction stays human-led.',item4Icon:'AI',item4Style:'white',
      }),
      block('StorySplitBlock', 'justin-home-story', {
        leftEyebrow:'About me',leftHeading:'I didn’t start my career behind a laptop.',
        leftText1:'My background is in mechanical engineering technology, CNC programming and tool & die design. That taught me to think about systems, tolerances, workflows and how things actually have to work in the real world.',
        leftText2:'I brought that same problem-solving mindset into web and mobile development.',
        rightEyebrow:'How I think',rightHeading:'Software should remove friction, not create more of it.',
        point1Title:'Understand the workflow first',point1Text:'Before writing code, I want to know what people are doing today, what is repetitive and where the process breaks down.',
        point2Title:'Build the simplest useful version',point2Text:'I would rather test a useful working flow early than spend months polishing the wrong solution.',
        point3Title:'Connect the systems already in use',point3Text:'Shopify, POS, APIs, databases and internal tools should work together instead of creating more duplicate work.',
        point4Title:'Keep changing the product when reality says it should change',point4Text:'Real usage exposes things a specification never will. The software should evolve around what users actually need.',
      }),
      block('ProcessRowsBlock', 'justin-home-ai-process', {
        eyebrow:'AI + Development',heading:'AI changes what one developer can accomplish.',
        text:'I use AI throughout the development process — not as a replacement for judgment, but as a way to move faster across more parts of a project.',
        note:'The business problem, product decisions, testing and final direction still need a human who understands what the software is supposed to accomplish.',
        row1Label:'RESEARCH',row1Text:'Explore technologies, approaches and business requirements quickly.',
        row2Label:'ARCHITECTURE',row2Text:'Break a product into workflows, data structures and technical components.',
        row3Label:'BUILD',row3Text:'Accelerate frontend, backend, integrations and rapid prototyping.',
        row4Label:'DEBUG',row4Text:'Investigate problems, compare approaches and iterate much faster.',
        row5Label:'REFINE',row5Text:'Improve UX, documentation, SEO, content and deployment workflows.',
      }),
      block('SkillsGridBlock', 'justin-home-skills', {
        eyebrow:'Technology',heading:'Tools I use to ship real work.',
        text:'I prefer showing technologies in the context of what I actually build rather than treating a skills list as the portfolio itself.',
        item1Title:'Frontend',item1Text:'HTML, CSS, JavaScript, React, Angular, TypeScript, responsive UI and mobile-first design.',
        item2Title:'Backend & Data',item2Text:'Node, Express, PHP, MySQL, Supabase, REST APIs and data-driven application workflows.',
        item3Title:'Commerce',item3Text:'Shopify, Shopify POS, Adobe Commerce / Magento, WordPress and ecommerce product workflows.',
        item4Title:'Delivery',item4Text:'Git, GitHub, Vercel, Linux, QA, deployment, SEO, analytics and AI-assisted development.',
      }),
      block('LargeCtaBlock', 'justin-home-large-cta', {
        eyebrow:'Open to the right opportunity',
        heading:'Need someone who can understand the problem and build the solution?',
        buttonText:'Get in touch →',
        buttonUrl:'/contact',
      }),
    ],
    root: { props: {} },
  },
  work: {
    content: [
      hero('justin-work-hero', 'Selected Work', 'Professional ecommerce, web and product work', 'A selection of commercial products, client work and professional ecommerce projects covering Shopify, Adobe Commerce / Magento, SEO, WordPress, frontend development and business workflow design.'),
      block('ProjectCardBlock', 'work-project-template', {
        logo:'https://nowsajdmbpxvlvrhopjg.supabase.co/storage/v1/object/public/site-assets/1790194715243-justconsigin-logo.png',logoAlt:'Website Shopify consignment software project mark',
        companyLabel:'Company / Product',companyName:'Website',category:'Shopify App · Consignment Software',eyebrow:'Product Development',
        heading:'Shopify consignment software connecting intake, products, POS sales and payouts.',headingLevel:'h2',
        summary:'Website is a Shopify-native consignment management application I designed and built to replace fragmented intake, product-entry, sales-tracking and payout workflows. It connects consignors, inventory, Shopify product creation, Shopify POS sales, commission calculations and payouts in one organized system.',
        roleLabel:'My role',roleText:'Product Strategy · UX/UI · Full-Stack Development · Shopify Integration · Supabase Architecture',
        audienceLabel:'Built for',audienceText:'Consignment, resale and secondhand stores using Shopify and Shopify POS',
        tags:'Shopify, React, Supabase, Shopify POS, REST APIs, Mobile Intake, Payouts, AI-Assisted Development',
        note:'Case study covering the product problem, workflow design, Shopify integration, application architecture, development process and product decisions.',
        buttonText:'View Website Case Study →',buttonUrl:'/work/template',panelPosition:'left',anchorId:'template',
      }),
      block('ProjectCardBlock', 'work-project-jill', {
        logo:'https://nowsajdmbpxvlvrhopjg.supabase.co/storage/v1/object/public/site-assets/1790194733233-jillandthebeanstalk-logo-thumb.png',logoAlt:'Jill and The Beanstalk ecommerce project mark',
        companyLabel:'Client / Ecommerce',companyName:'Jill & The Beanstalk',category:'Shopify Ecommerce · SEO · Growth',eyebrow:'Ecommerce Growth',
        heading:'Growing a Shopify store through SEO, ecommerce improvements and ongoing optimization.',headingLevel:'h2',
        summary:'My work with Jill & The Beanstalk spans Shopify storefront improvements, technical and on-page SEO, product and category content, search visibility, reviews, integrations and conversion-focused updates. The goal is consistent: make the store easier to discover, easier to shop and stronger as an online sales channel.',
        roleLabel:'My role',roleText:'Shopify Management · SEO · Ecommerce UX · Content · Integrations · Growth',
        audienceLabel:'Business',audienceText:'Children’s retail and resale business serving customers online and in-store',
        tags:'Shopify, SEO, Google Search Console, Judge.me, Doofinder, Content, Analytics, Conversion',
        note:'Case study focused on organic visibility, storefront improvements, ecommerce growth and the ongoing work behind a real operating store.',
        buttonText:'View Jill & The Beanstalk Case Study →',buttonUrl:'/work/jill-and-the-beanstalk',panelPosition:'right',anchorId:'jill-and-the-beanstalk',
      }),
      block('ProjectCardBlock', 'work-project-wheels', {
        logo:'https://wheelsauto.com/media/logo/stores/6/wheelsauto_logo_2.svg',logoAlt:'Wheels Automotive Dealer Supplies ecommerce project mark',
        companyLabel:'Professional Work',companyName:'Wheels Automotive',category:'Adobe Commerce / Magento · B2B Ecommerce',eyebrow:'B2B Ecommerce',
        heading:'Supporting the launch and ongoing improvement of a large automotive B2B ecommerce platform.',headingLevel:'h2',
        summary:'At Wheels Automotive Dealer Supplies, I work across Adobe Commerce / Magento frontend implementation, PageBuilder content, B2B account and checkout testing, QA, product and category SEO, merchandising content and launch support. The work spans Canadian, French and U.S. storefront requirements and ongoing coordination with the implementation vendor.',
        roleLabel:'My role',roleText:'Ecommerce Development · Frontend · QA · SEO · Content Architecture · Vendor Coordination',
        audienceLabel:'Built for',audienceText:'Automotive dealerships, dealer groups and automotive retail operations',
        tags:'Adobe Commerce, Magento 2, PageBuilder, B2B Ecommerce, HTML/CSS, QA, SEO, Product Content',
        note:'Case study covering the B2B launch, frontend work, QA, SEO, product/category systems and ongoing ecommerce improvements.',
        buttonText:'View Wheels Automotive Case Study →',buttonUrl:'/work/wheels-automotive',panelPosition:'left',anchorId:'wheels-automotive',
      }),
      block('ProjectCardBlock', 'work-project-wordpress', {
        logo:'/images/projects/wordpress-websites-mark.svg',logoAlt:'WordPress client websites project mark',
        companyLabel:'Client Websites',companyName:'WordPress Websites',category:'WordPress · Elementor · Small Business',eyebrow:'Web Development',
        heading:'Responsive WordPress websites designed around the needs of small businesses.',headingLevel:'h2',
        summary:'A grouped portfolio of WordPress client work including Sunluna Vacations and TOdecks.ca. The work covers responsive Elementor builds, navigation and page structure, forms and email delivery, client content and imagery, mobile usability, SEO and ongoing website support.',
        roleLabel:'My role',roleText:'WordPress Development · Elementor · Responsive Design · Forms · SEO · Site Support',
        audienceLabel:'Built for',audienceText:'Small businesses and service-based companies that need practical, maintainable websites',
        tags:'WordPress, Elementor, CSS, Responsive Design, Forms, SEO, HostPapa, Content Integration',
        note:'Collection page showing individual WordPress projects, the business requirement for each site and the specific work completed.',
        buttonText:'View WordPress Website Projects →',buttonUrl:'/work/wordpress-websites',panelPosition:'right',anchorId:'wordpress-websites',
      }),
    ],
    root: { props: {} },
  },
  'ai-development': {
    content: [
      hero('justin-ai-hero', 'AI + Development', 'AI is part of the workflow, not the product pitch.', 'The focus is on what becomes possible when AI is combined with domain knowledge, product decisions, software development and constant testing.'),
      heading('justin-ai-problem', 'Start with a real problem'),
      text('justin-ai-problem-copy', 'The process begins with understanding the workflow, constraints and people using the system before choosing technology or generating code.'),
      heading('justin-ai-build', 'Use AI to accelerate iteration'),
      text('justin-ai-build-copy', 'AI helps research approaches, reason through architecture, generate and refactor code, inspect failures and iterate faster. The system still has to be tested against the actual requirement.'),
      heading('justin-ai-result', 'Ship something that works'),
      text('justin-ai-result-copy', 'The value is not the prompt. The value is turning a business problem into a maintainable product that people can actually use.'),
    ],
    root: { props: {} },
  },
  about: {
    content: [
      block('HeroBlock', 'justin-about-hero', {
        eyebrow:'About Business Name',
        heading:'Developer, product builder and problem solver with an engineering background.',
        text:'I started in mechanical engineering technology, CNC programming and tool & die design, then retrained in web and mobile development. Today I work across ecommerce, custom software, Shopify, Adobe Commerce and AI-assisted development — building practical tools around real business workflows.',
        image:'',imageAlt:'',buttonText:'View my experience →',buttonUrl:'/experience',background:'light',
      }),
      block('StorySplitBlock', 'justin-about-story', {
        leftEyebrow:'Background',
        leftHeading:'I came into software from manufacturing and engineering.',
        leftText1:'My first career was built around mechanical engineering technology, CNC machining and programming, and tool & die design. That work taught me to think in systems, understand tolerances, solve practical problems and pay attention to how a process actually works from start to finish.',
        leftText2:'When I moved into web and mobile development, I brought that same mindset with me: understand the problem first, then build the simplest reliable solution around the people who have to use it.',
        rightEyebrow:'What I do now',
        rightHeading:'I build and improve digital products that have to work in the real world.',
        point1Title:'Product development',point1Text:'I designed and built Website, a Shopify-focused consignment application connecting intake, products, POS sales, commissions and payouts.',
        point2Title:'Professional ecommerce',point2Text:'At Wheels Automotive, I work with Adobe Commerce / Magento across frontend implementation, B2B workflows, QA, SEO, product content and launch support.',
        point3Title:'Client ecommerce + SEO',point3Text:'My work for Jill & The Beanstalk includes Shopify improvements, SEO, search visibility, content, integrations and ongoing ecommerce growth work.',
        point4Title:'Web + AI-assisted development',point4Text:'I also build WordPress sites and custom tools, using AI throughout research, architecture, coding, debugging and iteration to move from idea to working software faster.',
      }),
      block('SkillsGridBlock', 'justin-about-skills', {
        eyebrow:'What I bring',
        heading:'A mix of development, ecommerce and practical business problem-solving.',
        text:'I am most useful when the work crosses boundaries — code, UX, ecommerce, content, data and the real workflow behind the screen.',
        item1Title:'Development',item1Text:'React, JavaScript, TypeScript, Node, PHP, MySQL, Supabase, REST APIs and responsive frontend development.',
        item2Title:'Ecommerce',item2Text:'Shopify, Shopify POS, Adobe Commerce / Magento, WordPress, product workflows, SEO and storefront improvement.',
        item3Title:'Product thinking',item3Text:'Workflow mapping, data structure, UX decisions, rapid prototyping, testing and iteration around real user needs.',
        item4Title:'Delivery',item4Text:'GitHub, Vercel, QA, deployment, documentation, analytics and AI-assisted development from concept through launch.',
      }),
      block('LargeCtaBlock', 'justin-about-cta', {
        eyebrow:'Selected work',heading:'The best explanation of how I work is in the projects.',buttonText:'View my work →',buttonUrl:'/work',
      }),
    ],
    root: { props: {} },
  },
  experience: {
    content: [
      hero('justin-experience-hero', 'Experience', 'Web, mobile, ecommerce and product development.', 'React, JavaScript, TypeScript, Node, PHP, MySQL, WordPress, Shopify, Adobe Commerce and mobile development backed by an engineering and manufacturing background.'),
      heading('justin-experience-wheels', 'Wheels Automotive Dealers Supply'),
      text('justin-experience-wheels-copy', 'B2B ecommerce launch work, Adobe Commerce / Magento frontend implementation, QA, content, SEO and vendor coordination.'),
      heading('justin-experience-product', 'Independent product development'),
      text('justin-experience-product-copy', 'Designing and building Website from a real consignment-store workflow through Shopify integration, admin tooling, deployment and product marketing.'),
    ],
    root: { props: {} },
  },
  contact: {
    content: [
      hero('justin-contact-hero', 'Contact', 'Looking for a developer who understands both the code and the workflow?', 'Open to development roles, ecommerce work, product collaboration and selected freelance projects.'),
      cta('justin-contact-cta', 'Start a conversation.', 'Use the contact details on the finished site to reach out about a role or project.', 'Get in touch', '#contact'),
    ],
    root: { props: {} },
  },
};


const SUNWINGS_PAGE_EDITOR_DATA = {
  home: {
    content: [
      block('WebsiteHeroBlock', 'sw-home-hero', {
        eyebrow: 'Reliable • On-Time • Professional',
        heading: 'Moving & delivery,',
        accent: 'done right.',
        text: 'Residential moves, furniture delivery, junk removal and commercial transport across Toronto, the GTA, Hamilton and Niagara. Careful crews, upfront pricing, no surprises.',
        image: 'https://templatetransport.ca/wp-content/uploads/2026/01/cargo-van-1.png',
        imageAlt: 'Website Transport moving truck and crew',
        primaryButtonText: 'Get a Free Quote →',
        primaryButtonUrl: '/contact',
        secondaryButtonText: '',
        secondaryButtonUrl: '',
        showCallButton: true,
        showBreadcrumbs: false,
        background: 'white',
      }),
      block('WebsiteTrustBlock', 'sw-home-trust', {
        item1Icon:'star', item1Title:'Google reviews', item1Text:'Trusted by local customers',
        item2Icon:'dollar', item2Title:'Price-match guarantee', item2Text:'Fair, upfront quotes',
        item3Icon:'calendar', item3Title:'Flexible scheduling', item3Text:'Evenings & weekends',
        item4Icon:'pin', item4Title:'Toronto to Niagara', item4Text:'GTA, Hamilton & beyond',
        background:'white',
      }),
      block('WebsiteServicesGridBlock', 'sw-home-services', {
        eyebrow: 'What we do',
        heading: 'One call for every move.',
        text: 'From a single couch to a full warehouse transfer, Website brings the truck, the crew and the care.',
        align: 'center',
        limit: '0',
        buttonText: '',
        buttonUrl: '/services',
        background: 'white',
      }),
      block('WebsiteStepsBlock', 'sw-home-steps', {
        eyebrow: 'How it works',
        heading: 'Booked in three steps.',
        text: '',
        step1Title:'Tell us the job',
        step1Text:'Send pickup, drop-off, date and what’s moving. Takes about two minutes.',
        step2Title:'Get your price',
        step2Text:'We confirm the details and send a clear, upfront quote. No hidden fees.',
        step3Title:'We move it',
        step3Text:'The crew shows up on time, protects everything and places it where you want it.',
        background:'soft',
      }),
      block('WebsiteSplitFeatureBlock', 'sw-home-business', {
        eyebrow:'For businesses',
        heading:'A transport partner you can schedule on.',
        text:'Retailers, warehouses, contractors and property managers use Website for one-off projects and recurring routes.',
        image:'https://templatetransport.ca/wp-content/uploads/2026/02/van-loading-file-cabinet.jpg',
        imageAlt:'Website commercial transport',
        imagePosition:'left',
        checklist:'Warehouse transfers\nContainer unloading\nRetail deliveries\nOffice relocations\nEquipment transport\nRecurring routes',
        buttonText:'Commercial transport →',
        buttonUrl:'/services/commercial-transport',
        background:'white',
      }),
      block('WebsitePriceBandBlock', 'sw-home-pricing', {
        eyebrow:'Pricing',
        heading:'Straight answers on price.',
        text:'Every quote is based on crew size, truck time and distance. Found a lower written quote? We’ll match it.',
        buttonText:'See pricing →',
        buttonUrl:'/pricing',
        card1Label:'Small moves & deliveries',
        card1Value:'Get a quote',
        card1Note:'single items, studios',
        card2Label:'Truck + crew',
        card2Value:'Upfront pricing',
        card2Note:'based on your job',
        removeTopSpace:true,
        background:'white',
      }),
      block('WebsiteLocationsGridBlock', 'sw-home-locations', {
        eyebrow:'Service areas',
        heading:'From Toronto to Niagara.',
        text:'Local crews who know the buildings, highways and condo elevator rules.',
        detailed:false,
        buttonText:'View all service areas →',
        buttonUrl:'/locations',
        background:'white',
      }),
      block('WebsiteReviewsBlock', 'sw-home-reviews', {
        eyebrow:'Reviews',
        heading:'What customers say.',
        review1Text:'', review1Name:'', review1Stars:'5',
        review2Text:'', review2Name:'', review2Stars:'5',
        review3Text:'', review3Name:'', review3Stars:'5',
        background:'soft',
      }),
      block('WebsiteBlogGridBlock', 'sw-home-blog', {
        eyebrow:'Moving tips',
        heading:'From the Website blog.',
        limit:'3',
        showCategories:false,
        background:'white',
      }),
    ],
    root: { props: {} },
  },

  services: {
    content: [
      block('WebsiteHeroBlock', 'sw-services-hero', {
        eyebrow:'Services',
        heading:'Moving, delivery & transport services',
        accent:'',
        text:'Residential, commercial and warehouse services across Toronto, the GTA, Hamilton and Niagara.',
        image:'https://templatetransport.ca/wp-content/uploads/2026/02/cargo-van-driveway1.png',
        imageAlt:'Website Transport services',
        primaryButtonText:'Get a Free Quote →',
        primaryButtonUrl:'/contact',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:true,
        breadcrumbLabel:'Services',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsiteServicesGridBlock', 'sw-services-grid', {
        eyebrow:'All services',
        heading:'What Website can do for you.',
        text:'Choose a service to see details, coverage and what is included.',
        align:'left',
        limit:'0',
        buttonText:'',
        buttonUrl:'/services',
        background:'white',
      }),
      block('WebsiteStepsBlock', 'sw-services-steps', {
        eyebrow:'How it works',
        heading:'Booked in three steps.',
        text:'',
        step1Title:'Tell us the job',
        step1Text:'Send pickup, drop-off, date and what’s moving.',
        step2Title:'Get your price',
        step2Text:'We confirm the details and send a clear quote.',
        step3Title:'We move it',
        step3Text:'The crew arrives, protects the load and completes the job.',
        background:'soft',
      }),
    ],
    root:{props:{}},
  },

  locations: {
    content: [
      block('WebsiteHeroBlock', 'sw-locations-hero', {
        eyebrow:'Service Areas',
        heading:'Service areas: Toronto to Niagara',
        accent:'',
        text:'Pick your city to see local services, neighbourhoods we cover and answers to local questions.',
        image:'https://templatetransport.ca/wp-content/uploads/2026/01/cargo-van-1.png',
        imageAlt:'Website Transport service areas',
        primaryButtonText:'Get a Free Quote →',
        primaryButtonUrl:'/contact',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:true,
        breadcrumbLabel:'Service Areas',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsiteLocationsGridBlock', 'sw-locations-grid', {
        eyebrow:'Coverage',
        heading:'Find your service area.',
        text:'Published Location Posts appear here automatically.',
        detailed:true,
        buttonText:'',
        buttonUrl:'/locations',
        background:'white',
      }),
      block('WebsiteQuoteFormBlock', 'sw-locations-quote', {
        eyebrow:'Not listed?',
        heading:'Moving somewhere else in Ontario?',
        text:'Tell us the route and we’ll quote it.',
        buttonText:'',
        buttonUrl:'/contact',
        compact:true,
        background:'soft',
      }),
    ],
    root:{props:{}},
  },

  pricing: {
    content: [
      block('WebsiteHeroBlock', 'sw-pricing-hero', {
        eyebrow:'Pricing',
        heading:'Straight answers on price',
        accent:'',
        text:'Upfront quotes based on crew size, truck time and distance, backed by our price-match guarantee.',
        image:'https://templatetransport.ca/wp-content/uploads/2026/02/van-loading-file-cabinet.jpg',
        imageAlt:'Website Transport pricing',
        primaryButtonText:'Get a Free Quote →',
        primaryButtonUrl:'/contact',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:true,
        breadcrumbLabel:'Pricing',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsitePricingCardsBlock', 'sw-pricing-cards', {
        eyebrow:'Pricing',
        heading:'Choose the job type.',
        text:'Final pricing is based on the details of your move or delivery.',
        featuredCard:'2',
        card1Title:'Small moves & delivery',
        card1Subtitle:'Single items, Marketplace pickups, studios',
        card1Amount:'Quote',
        card1Note:'based on the job',
        card1Features:'1–2 movers\nCargo van\nBlanket wrapping\nPlacement in room',
        card1ButtonText:'Get a quote',
        card1ButtonUrl:'/contact',
        card2Title:'Truck + 2 movers',
        card2Subtitle:'Most 1–2 bedroom moves',
        card2Amount:'Quote',
        card2Note:'upfront pricing',
        card2Features:'2 movers\nTruck & equipment\nWrapping & protection\nDisassembly & reassembly',
        card2ButtonText:'Get a quote',
        card2ButtonUrl:'/contact',
        card3Title:'Larger moves',
        card3Subtitle:'Houses, commercial and larger jobs',
        card3Amount:'Quote',
        card3Note:'based on crew and time',
        card3Features:'Larger crew\nTruck & equipment\nWrapping & protection\nBuilt for bigger jobs',
        card3ButtonText:'Get a quote',
        card3ButtonUrl:'/contact',
        footnote:'',
        background:'white',
      }),
      block('WebsitePricingFactorsBlock', 'sw-pricing-factors', {
        eyebrow:'What affects your price',
        heading:'No surprises on the bill.',
        text:'',
        checklist:'Crew size and hours on the job\nDistance between pickup and drop-off\nStairs, long carries and elevator wait times\nPacking, wrapping and specialty items',
        guaranteeEyebrow:'Price-match guarantee',
        guaranteeHeading:'Found a lower written quote?',
        guaranteeText:'Show us a lower written quote for the same job and we’ll match it.',
        background:'soft',
      }),
      block('WebsiteFaqBlock', 'sw-pricing-faq', {
        eyebrow:'Pricing questions',
        heading:'What affects your quote?',
        question1:'What changes the price of a move?',
        answer1:'Crew size, time on the job, travel distance, stairs, elevators, long carries, packing and specialty items can all affect the final quote.',
        question2:'Do you provide upfront quotes?',
        answer2:'Yes. Send the job details and Website will confirm the scope and quote before the work is booked.',
        background:'soft',
      }),
      cta('sw-pricing-cta','Found a lower written quote?','Show us a comparable written quote for the same job and we’ll match it.','Get a quote →','/contact'),
    ],
    root:{props:{}},
  },

  contact: {
    content: [
      block('WebsiteHeroBlock', 'sw-contact-hero', {
        eyebrow:'Contact',
        heading:'Get your free quote',
        accent:'',
        text:'Tell us what’s moving and where. We reply fast, usually the same day.',
        image:'https://templatetransport.ca/wp-content/uploads/elementor/thumbs/happy-couple-move-rjw992tbb61z2n9hhbnvscs9srjnmxwvlts7dp1qbi.jpg',
        imageAlt:'Website Transport contact',
        primaryButtonText:'',
        primaryButtonUrl:'',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:true,
        breadcrumbLabel:'Contact',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsiteContactBlock', 'sw-contact-panel', {
        callTitle:'Call or text',
        emailTitle:'Email',
        hours:'',
        areaTitle:'Service area',
        areaText:'Toronto, the GTA, Halton, Hamilton & Niagara',
        background:'white',
      }),
    ],
    root:{props:{}},
  },

  blog: {
    content: [
      block('WebsiteHeroBlock', 'sw-blog-hero', {
        eyebrow:'Moving Tips',
        heading:'Moving tips & guides',
        accent:'',
        text:'Straight advice on pricing, condo moves, deliveries and planning your move.',
        image:'https://templatetransport.ca/wp-content/uploads/2026/02/pexels-photo-7464708-7464708.jpg',
        imageAlt:'Website Transport moving tips',
        primaryButtonText:'',
        primaryButtonUrl:'',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:false,
        breadcrumbLabel:'Moving Tips',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsiteBlogGridBlock', 'sw-blog-grid', {
        eyebrow:'Latest',
        heading:'Moving tips from Website.',
        limit:'12',
        showCategories:true,
        background:'white',
      }),
    ],
    root:{props:{}},
  },

  privacy: {
    content: [
      block('WebsiteHeroBlock', 'sw-privacy-hero', {
        eyebrow:'Legal',
        heading:'Privacy Policy',
        accent:'',
        text:'',
        image:'',
        imageAlt:'',
        primaryButtonText:'',
        primaryButtonUrl:'',
        secondaryButtonText:'',
        secondaryButtonUrl:'',
        showCallButton:false,
        breadcrumbLabel:'Privacy Policy',
        showBreadcrumbs:true,
        background:'white',
      }),
      block('WebsiteRichTextBlock', 'sw-privacy-copy', {
        heading:'',
        body:'Website Transport uses information submitted through this website to respond to quote requests and service enquiries.\n\nAdditional privacy terms can be maintained here before production launch.',
        maxWidth:'820',
        background:'white',
      }),
    ],
    root:{props:{}},
  },
};

export function getInitialPageBuilderData(id, siteKey = 'template') {
  const source = siteKey === 'template'
    ? JUSTIN_PAGE_EDITOR_DATA
    : siteKey === 'template'
      ? SUNWINGS_PAGE_EDITOR_DATA
      : PAGE_EDITOR_DATA;
  return source[id] || { content: [], root: { props: {} } };
}
